- name: Przygotowanie stacji HIL (Raspberry Pi 5)
  hosts: all
  become: yes
  tasks:
    - name: Python3 jest obecny
      apt: name=python3 state=latest
      
    - name: Nadaj uprawnienia do portu szeregowego dla Runnera 
      user:
        name: gitlab-runner
        groups: dialout
        append: yes